# Generated by Django 5.2.17 on 2026-09-23 02:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentevent',
            name='provider_status',
            field=models.CharField(choices=[('NOT_SENT', 'Not sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown')], default='NOT_SENT', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='program',
            name='country_code',
            field=models.CharField(default='SD', max_length=2),
        ),
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='program',
            name='timezone',
            field=models.CharField(default='UTC', max_length=80),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('REFUNDED', 'Refunded'), ('RETRY', 'Retry'), ('EXCEPTION', 'Exception')], max_length=20),
        ),
        migrations.CreateModel(
            name='AISignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=120)),
                ('entity_id', models.CharField(max_length=120)),
                ('signal_type', models.CharField(max_length=120)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('reason', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(blank=True, max_length=80)),
                ('rule_version', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed'), ('ACCEPTED', 'Accepted')], default='OPEN', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_signals', to='core.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_ai_signals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_signals', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=120)),
                ('action_name', models.CharField(max_length=120)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_rules', to='core.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_rules', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('planned_action', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRY_RUN', 'Dry run'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='BLOCKED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_executions', to='core.tenant')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='core.automationrule')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PARTIAL_SUCCESS', 'Partial success'), ('PARTIAL_FAILURE', 'Partial failure'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RECONCILED', 'Reconciled')], default='DRAFT', max_length=30)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='core.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='paymentinstruction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructions', to='core.paymentbatch'),
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('AMOUNT_MISMATCH', 'Amount mismatch'), ('STATUS_MISMATCH', 'Status mismatch'), ('MISSING_REFERENCE', 'Missing reference'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('DUPLICATE', 'Duplicate'), ('UNRESOLVED', 'Unresolved')], max_length=40)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('expected_status', models.CharField(blank=True, max_length=30)),
                ('actual_status', models.CharField(blank=True, max_length=30)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='core.paymentinstruction')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='core.program')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_reconciliation_items', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('DUPLICATE_REVIEW', 'Duplicate review'), ('RISK_REVIEW', 'Risk review'), ('ELIGIBILITY_REVIEW', 'Eligibility review'), ('PAYMENT_EXCEPTION', 'Payment exception'), ('RECONCILIATION', 'Reconciliation'), ('COMPLAINT_ESCALATION', 'Complaint escalation'), ('DATA_QUALITY', 'Data quality')], max_length=40)),
                ('entity_type', models.CharField(max_length=120)),
                ('entity_id', models.CharField(max_length=120)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_tasks', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_tasks', to='core.program')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_tasks', to='core.tenant')),
            ],
        ),
    ]
