# Generated by Django 5.2.17 on 2026-09-25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0002_paymentevent_provider_status_and_more")]

    operations = [
        migrations.CreateModel(
            name="PDMResponse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channel", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=255)),
                ("received_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("amount_received", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("access_problem_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("complaint_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("satisfaction", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_pdm_responses", to=settings.AUTH_USER_MODEL)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pdm_responses", to="core.program")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pdm_responses", to="core.tenant")),
            ],
        ),
    ]
