# Generated by Django 5.2.17 on 2026-09-25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0003_pdmresponse")]

    operations = [
        migrations.CreateModel(
            name="ProgramActivity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("workstream", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(choices=[("NOT_STARTED", "Not started"), ("IN_PROGRESS", "In progress"), ("BLOCKED", "Blocked"), ("COMPLETED", "Completed")], default="NOT_STARTED", max_length=20)),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_end", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("actual_end", models.DateField(blank=True, null=True)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("risk", models.CharField(blank=True, max_length=20)),
                ("is_milestone", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_activities", to=settings.AUTH_USER_MODEL)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assigned_activities", to=settings.AUTH_USER_MODEL)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="activities", to="core.program")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="activities", to="core.tenant")),
            ],
            options={"constraints": [models.CheckConstraint(condition=models.Q(("progress__gte", 0), ("progress__lte", 100)), name="program_activity_progress_range")]},
        ),
        migrations.CreateModel(
            name="ActivityDependency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("relationship_type", models.CharField(choices=[("FS", "Finish to start")], default="FS", max_length=10)),
                ("lag_days", models.IntegerField(default=0)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_activity_dependencies", to=settings.AUTH_USER_MODEL)),
                ("predecessor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="successor_dependencies", to="core.programactivity")),
                ("successor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="predecessor_dependencies", to="core.programactivity")),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("predecessor", "successor"), name="unique_activity_dependency")]},
        ),
    ]
