# Generated by Django 5.2.17 on 2026-09-30 08:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_reviewer_decision_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cash_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='nfi_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='other_assistance_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CashEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(max_length=3)),
                ('conditions', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_entitlements', to='core.beneficiary')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cash_entitlements', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_entitlements', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('distribution_team', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('evidence', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('exceptions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_distribution_events', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_events', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ELIGIBLE', 'Eligible'), ('INELIGIBLE', 'Ineligible'), ('ON_HOLD', 'On hold')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='household_eligibility_decisions', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_decisions', to='core.household')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='household_eligibility', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='household_enrollment_decisions', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='household_enrollments', to='core.household')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='household_enrollments', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='NFIItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(default='ITEM', max_length=80)),
                ('unit', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_nfi_items', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfi_items', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='NFIEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('conditions', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISTRIBUTED', 'Distributed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfi_entitlements', to='core.beneficiary')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_nfi_entitlements', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfi_entitlements', to='core.program')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='core.nfiitem')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_quantity', models.PositiveIntegerField()),
                ('actual_quantity', models.PositiveIntegerField(default=0)),
                ('delivery_status', models.CharField(max_length=30)),
                ('evidence', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_issues', to='core.beneficiary')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_issues', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='core.distributionevent')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='core.nfientitlement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='core.nfiitem')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_quantity', models.PositiveIntegerField()),
                ('allocated_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_allocations', to='core.beneficiary')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_allocations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.distributionevent')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.nfientitlement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.nfiitem')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('responsible_team', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_warehouses', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entry'), ('ALLOCATION', 'Allocation'), ('ISSUE', 'Issue'), ('DISTRIBUTION', 'Distribution'), ('RETURN', 'Return'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.nfiitem')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.program')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='nfiitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.warehouse'),
        ),
    ]
