# Generated by Django 5.2.17 on 2026-09-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_program_cash_enabled_program_nfi_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionevent',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_events', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assistance_modality',
            field=models.CharField(choices=[('CASH', 'Payment'), ('NFI', 'NFI'), ('CASH_NFI', 'Payment + NFI')], default='CASH', max_length=12),
        ),
        migrations.AddField(
            model_name='nfientitlement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nfi_entitlements', to='core.warehouse'),
        ),
        migrations.AddField(
            model_name='nfiitem',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nfiitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
