# Generated by Django 5.2.17 on 2026-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_distributionevent_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionissue',
            name='delivery_status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PARTIALLY_RECEIVED', 'Partially received'), ('NOT_RECEIVED', 'Not received'), ('NO_SHOW', 'No show'), ('REJECTED', 'Rejected'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('RESCHEDULED', 'Rescheduled')], max_length=30),
        ),
    ]
