# Generated by Django 5.2.17 on 2026-10-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_household_centered_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ENROLLED', 'Enrolled'), ('ACCEPTED', 'Accepted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
    ]
